name: Build eS-Snapshots-lede
on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    name: Build ${{ matrix.model }}-${{ matrix.tag.version }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          #- nanopi-r4s
          #- nanopi-r5s
          - x86_64
        tag:
          - type: dev
            version: snapshots
        target:
          - arch: "x86_64"
            target: "x86"
            kernel: "6.18"

    steps:
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        echo build_dir="/builder" >> "$GITHUB_ENV"
        if [[ "${{ matrix.model }}" == nanopi-* ]]; then
          echo ccache_model=nanopi-r5s >> "$GITHUB_ENV"
        else
          echo ccache_model=${{ matrix.model }} >> "$GITHUB_ENV"
        fi

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Free disk space
      uses: sbwml/actions@free-disk
      with:
        build-mount-path: /builder

    - name: Build System Setup
      uses: sbwml/actions@openwrt-build-setup

    - name: Install LLVM
      uses: sbwml/actions@install-llvm

    - name: Restore Cached
      uses: actions/cache/restore@v4
      with:
        path: /builder/.ccache
        key: ${{ matrix.tag.version }}-${{ env.ccache_model }}

    - name: Checkout build scripts
      uses: actions/checkout@v4
      with:
        repository: ilxp/eS_lede_build_script
        token: ${{ secrets.workflow_token }}
        ref: main
        path: oprx-es

    - name: Set date
      id: date
      run: |
        echo "date1=$(TZ=UTC-8 date +'%m.%d.%Y')" >> $GITHUB_ENV

    - name: Compile OpenWrt
      id: compile
      continue-on-error: true
      working-directory: /builder
      run: |
        export ENABLE_UHTTPD=y
        #export KERNEL_CLANG_LTO=y
        #export BUILD_FAST=y
        #export ENABLE_CCACHE=y
        #export ENABLE_OTA=y
        #export ENABLE_BPF=y
        #export ENABLE_LTO=y
        #export ENABLE_LRNG=y
        #export USE_GCC15=y
        #export ENABLE_MOLD=y
        #export ENABLE_UHTTPD=y

        cd /builder/oprx-es/openwrt
        chmod +x build-oprx.sh
        bash ./build-oprx.sh ${{ matrix.tag.type }} ${{ matrix.model }}

        build_date=$(date "+%Y-%m-%d")
        echo "build_date=$build_date" >> $GITHUB_ENV

    - name: Extensive logs after a failed compilation
      if: steps.compile.outcome == 'failure'
      working-directory: /builder
      run: |
        cd openwrt
        make V=s IGNORE_ERRORS="n m"

    - name: Prepare Firmware Files
      working-directory: /builder
      run: |
        mkdir -p rom info
        if [ "${{ matrix.model }}" = "nanopi-r4s" ]; then
          cp -a openwrt/bin/targets/rockchip/*/*.img.gz rom/
          cp -a openwrt/bin/targets/rockchip/*/*-r4s.manifest info/manifest.txt
          cp -a openwrt/bin/targets/rockchip/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum * > ../info/sha256sums.txt
        elif [ "${{ matrix.model }}" = "nanopi-r5s" ]; then
          cp -a openwrt/bin/targets/rockchip/*/*.img.gz rom/
          cp -a openwrt/bin/targets/rockchip/*/*.manifest info/manifest.txt
          cp -a openwrt/bin/targets/rockchip/*/config.buildinfo info/config.buildinfo
          cd rom && sha256sum * > ../info/sha256sums.txt
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          cp -a openwrt/bin/targets/x86/*/OprX-*.img.gz rom/
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        fi

    - name: Create release
      uses: ncipollo/release-action@v1.21.0
      with:
        name: Firmware
        allowUpdates: true
        tag: firmware
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: |
          ${{ env.build_dir }}/rom/*

    - name: Release kmods
      if: ${{ matrix.model != 'nanopi-r4s' }}
      uses: ncipollo/release-action@v1.14.0
      with:
        name: Kmod
        allowUpdates: true
        tag: kmod
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: |
          ${{ env.build_dir }}/openwrt/*-*.tar.gz

    - name: Sync kernel modules
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.workflow_token }}
        repository: ilxp/oprx-es_core
        event-type: sync

    - name: Release soup
      uses: ncipollo/release-action@main
      with:
        name: Firmware
        allowUpdates: true
        tag: firmware
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: ${{ env.build_dir }}/openwrt/soup/*.json
